# Topic names
state_topic: "/ur3_cartesian_velocity_controller/ee_state"
command_topic: "/ur3_cartesian_velocity_controller/command_cart_vel"

# Static gain
Dx: 3
Dy: 3
Dz: 3

# Euclidean distance gain
eucl_flag: false
D_eucl: 0.2

# Exponential gain
exp_flag: false
Ka: 10
Kb: 30
min_dis: 0.0
max_dis: 0.2
Ka_exp: 30
Kb_exp: 34
c: 0

# Self collision distance
self_collision_limit: 0.23
z_limit: 0.23

# Extention distance
overextension_limit: 0.56 #0.56-0.03

# Consecutive control points distance
consecutive_points_distance: 0.02

# sim or real HW
sim: false
