# Static gain
Dx: 1
Dy: 1
Dz: 1
Kx: 3
Ky: 3
Kz: 3

# Offsets for robot workspace
xOffset: 0.41
yOffset: 0.0
zOffset: 0.0

# Offset for desired robot distance
xGoal: 0.0
yGoal: 0.0
zGoal: 0.0

# sim or real HW
sim: false
