# Topic names
state_topic: "/manos_cartesian_velocity_controller/ee_state"
command_topic: "/manos_cartesian_velocity_controller/command_cart_vel"

# Static gain
Dx: 40
Dy: 40
Dz: 40
Kx: 10
Ky: 10
Kz: 10

# Self collision limits
self_collision_limit: 0.23
z_limit: 0.23

# Overextension limits
overextension_limit: 0.55

# rotation
theta: 0

# Consecutive control points distance
consecutive_points_distance: 0.02