# Static gain
Dx: 45
Dy: 45
Dz: 45
Kx: 10
Ky: 10
Kz: 10

# Self collision distance
self_col_dis: 0.23
z_dis: 0.23

# Extention distance
extention_dis: 0.60 #0.56-0.03

# Control scheme
human_vel: false

# rotation
theta: 0