# Static gain
Dx: 2
Dy: 2
Dz: 2

# Offsets for robot workspace
xOffset: 0.6
yOffset: 0.4
zOffset: 0.0

# Euclidean distance gain
eucl_flag: false
D_eucl: 0.2

# Exponential gain
exp_flag: false
Ka: 10
Kb: 30
min_dis: 0.0
max_dis: 0.2
Ka_exp: 30
Kb_exp: 34
c: 0

# sim or real HW
sim: true
