# Static gain
Dx: 4
Dy: 4
Dz: 4

# Euclidean distance gain
eucl_flag: false
D_eucl: 0.2

# Exponential gain
exp_flag: false
Ka: 10
Kb: 30
min_dis: 0.0
max_dis: 0.2
Ka_exp: 30
Kb_exp: 34
c: 0

# Self collision distance
self_col_dis: 0.23
z_dis: 0.23

# Extention distance
extention_dis: 0.56 #0.56-0.03

# sim or real HW
sim: false
